version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: gorbac-sample
    volumes:
      - '.:/go/app'
    ports:
      - '8022:8022'
    tty: true
    stdin_open: true
